server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/WF1683497569/tensquare.git
  rabbitmq:
    host: 192.168.159.129
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh