server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wf1683497569/tensquare.git
  rabbitmq:
    host: 106.52.236.254
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh